In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
X, y = load_iris(return_X_y=True)

In [3]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [4]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

In [5]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print(f"Accuracy :{accuracy_score(y_pred, y_test)}")
print(f"Classification Report :\n{classification_report(y_pred, y_test)}")
print(f"Confusion Matrix :\n{confusion_matrix(y_pred, y_test)}")

Accuracy :1.0
Classification Report :
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

Confusion Matrix :
[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
